Repository Lazarus-org/dj-user-behavior, pull requests merged in 2025-04, with the labels that each got.

#81 Feat/report view
  pyproject.toml
  user_behavior/constants/default_settings.py
  user_behavior/settings/checks.py
  user_behavior/settings/conf.py
  user_behavior/utils/user_agent.py
  user_behavior/views.py
Labels: enhancement

#85 Refactor/main
  user_behavior/api/routers/__init__.py
  user_behavior/mixins/api/config_api_attrs.py
  user_behavior/tests/settings/test_checks.py
  user_behavior/tests/urls.py
  user_behavior/urls.py
Labels: enhancement

#87 fix(view): convert duration time to minutes
  user_behavior/views.py
Labels: bug

#90 fix(views): Unsupported operation between datetime & int
  user_behavior/views.py
Labels: bug

#92 style: Update code style to pass pre-commit hooks validations
  user_behavior/static/css/report.css
  user_behavior/templates/report.html
  user_behavior/urls.py
  user_behavior/utils/user_agent.py
Labels: bug

#93 docs(README): Add report view section & related documentations
  README.md
Labels: documentation

#98 Fix/report template
  user_behavior/static/css/report.css
  user_behavior/templates/report.html
Labels: bug, enhancement

#100 style: Update code style to pass linting validations
  user_behavior/static/css/report.css
  user_behavior/templates/report.html
Labels: bug

#105 chore(tox): Add support for Django new version 5.2
  tox.ini
Labels: dependencies

#107 :zap::art: fix(Style):Replace datalist with custom dropdown, update c…
  user_behavior/static/css/report.css
  user_behavior/templates/report.html
Labels: enhancement

#109 Chore/pre commit
  .pre-commit-config-ci.yaml
  .pre-commit-config.yaml
  user_behavior/templates/report.html
Labels: dependencies

#113 chore(tox): Add support for drf version 3.16
  tox.ini
Labels: dependencies
